import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useTheme } from '../contexts/ThemeContext'
import CustomizedSwitches from '../components/Switch/Switch'
import Header from '../components/Header/Header'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { theme, toggleTheme } = useTheme();
  console.log(theme)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <button onClick={toggleTheme}>Toggle Theme</button>
      <CustomizedSwitches />

    </>
  )
}
